services:
  - type: web
    name: dash-app
    env: python
    buildCommand: |
      apt-get update && apt-get install -y wget
      pip install -r requirements.txt
      python -m plotly_get_chrome
    startCommand: gunicorn main:server  --workers 1 --threads 4
#    envVars:
#      - key: REDIS_URL
#        fromService:
#          name: dash-redis
#          type: redis
#          property: connectionString


#  - type: worker
#    name: celery-worker
#    buildCommand: pip install -r requirements.txt
#    startCommand: celery -A celery_worker.celery_app worker --loglevel=info
#    runtime:
#    envVars:
#      - key: REDIS_URL
#        fromService:
#          name: dash-redis
#          type: redis
#          property: connectionString

